apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - image: mysql:8.0.28
        name: mysql
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: msvc-usuarios
                key: db_database
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: msvc-usuarios
                key: db_password
        volumeMounts:
          - name: data-mysql
            mountPath: /var/lib/mysql
      volumes:
        - name: data-mysql
          persistentVolumeClaim:
            claimName: mysql-pvc