apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
spec:
  replicas: 1
  selector:
    matchLabels:
      role: postgresdb
  template:
    metadata:
      labels:
        role: postgresdb
    spec:
      containers:
        - name: postgresdb
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: db_database
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: msvc-cursos
                  key: db_password
          volumeMounts:
            - name: data-postgres
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: postgres-pvc