version: "3.9"

services:
  msvc_usuarios:
    container_name: usuarios
    image: danielvza/usuarios:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-usuarios/Dockerfile
    ports:
      - 8001:8001
    env_file:
      - ./msvc-usuarios/.env
    networks:
      - spring
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.28
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: msvc_usuarios
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - data-mysql:/var/lib/mysql
    networks:
      - spring

volumes:
  data-mysql:
    name: data-mysql

networks:
  spring:
    name: spring