apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: ""
#  storageClassName: standard
  accessModes:
    - ReadWriteMany
#    - ReadWriteOne
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-05e8b2c2de29085d8
#    - ReadWriteOnce
#  hostPath:
#    path: /var/lib/mysql
#    type: DirectoryOrCreate