apiVersion: v1
kind: Secret
metadata:
  name: msvc-usuarios
type: Opaque
data:
  db_username: cm9vdA==
  db_password: cm9vdA==

---
apiVersion: v1
kind: Secret
metadata:
  name: msvc-cursos
type: Opaque
data:
  db_username: cG9zdGdyZXM=
  db_password: cm9vdA==